### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by bxb100** [bxb100/github-workflow-plugin#1]
- [x] 🔼 修复 complete 有时候无法获取当前 PSI 的问题
  - 猜测可能是 debug 进入判断 project contentFile 时切换 IDEA 窗口导致的, 下移 breakpoint 暂时没出现这个情况
- [ ] 🔴 加日志
- [ ] 目前全是使用 `atomReference` 会导致 UI 和实际显示错位, 比如多个 projects 的情况
- [ ] 优化 yml 的识别, 使用 YAML 插件的方法来获取 element, 而不是正则
- [x] 优化线程, 现在使用 `completeFuture` 来异步下载
- [ ] 优化 GitHub 的 token 调用, 现在依赖 GitHub 插件的 token
- [ ] 下载 github 文件的时候给个进度条, 失败也要给个提示
- [ ] 🔽 缩小 `${tmp}/ide_github_workflow_plugin` 下面 yml(json) 的体积

**Comment by bxb100** [comment]
- [ ] 参考项目 <https:github.com/zalando/intellij-swagger>
   - [ ] 增加 local file 的 reference
